name: MACKER Cron Job

on:
  schedule:
    # Run at 10:00 AM EST (15:00 UTC)
    - cron: "0 15 * * *"
    # Run at 10:00 PM EST (03:00 UTC)
    - cron: "0 3 * * *"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run MACKER
      env:
        NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
        CREDENTIALS_GMAIL: ${{ secrets.CREDENTIALS_GMAIL }}
        SERVICE_KEY: ${{ secrets.SERVICE_KEY }}
      run: |
        python main.py --update
