name: MACKER Cron Job

on:
  # Schedule: Run at 10:00 AM EST and 10:00 PM EST
  schedule:
    - cron: "0 15 * * *"  # 10:00 AM EST (15:00 UTC)
    - cron: "0 3 * * *"   # 10:00 PM EST (03:00 UTC)
  workflow_dispatch:  # Allows manual runs of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9  # Ensure this matches your project’s requirements

    # Step 3: Decode token.pickle
    - name: Decode token.pickle
      run: |
        echo "${{ secrets.TOKEN_PICKLE }}" | base64 -d > token.pickle

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 5: Run the MACKER script
    - name: Run MACKER
      env:
        SERVICE_KEY: ${{ secrets.SERVICE_KEY }}
        CREDENTIALS_GMAIL: ${{ secrets.CREDENTIALS_GMAIL }}
        SPREAD_SHEET: "Macker"
        NOTIFICATION_EMAIL: "noahkornberg@gmail.com"
      run: |
        python main.py --update
